FROM ubuntu:22.04
LABEL org.opencontainers.image.authors="bds_uplimit@fastmail.fm"
LABEL org.opencontainers.image.server_type="edge_server"
RUN apt update
RUN apt install nginx -y
COPY config/nginx.conf /etc/nginx/
COPY web_content/ /var/www
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
